### PR TITLE
Bump base upper bound

### PR DESCRIPTION
**Pull request by bgamari**
For GHC 9.4.

### CODE REVIEW

**Comment by bgamari** [comment]
@judah, ping

**Comment by bgamari** [comment]
@judah, ping.

Alternatively, do feel free to grant me rights to this repository and the Hackage package and I would be happy to manage this myself.

**Comment by fluesvamp** [comment]
don't know if the Changelog should be updated

anyways, here's a typo fix from closed PR

```
sed -i "s/Applys/Applies/g" terminfo/System/Console/Terminfo/Base.hs
```

**Comment by bgamari** [comment]
> don't know if the Changelog should be updated
> 
> anyways, here's a typo fix from a closed PR
> 
> ```
> sed -i "s/Applys/Applies/g" terminfo/System/Console/Terminfo/Base.hs
> ```

Thanks, I have committed this fix.

The changelog shouldn't need to be updated since this MR is merely a Hackage revision.

**Pull request merged**
